version: 2

sources:
  - name: erp
    schema: sap_adw
    description: Fonte de dados de vendas do SAP Adventure Works
    tables:

      - name: employee 
        columns:
          - name: businessentityid # Utilizando o businessentityid no teste, pois cada Funcionário deverá ter um id único.
            tests:
              - unique
              - not_null

      - name: person 
        columns:
          - name: businessentityid # Utilizando o businessentityid no teste, pois cada Pessoa deverá ter um id único.
            tests:
              - unique
              - not_null

      - name: salesperson
        columns:
          - name: rowguid # Utilizando o rowguid no teste, para previnir casos de um vendedor atuar em mais de um território o que geraria duas linhas nessa tabela com o mesmo businessentityid
            tests:
              - unique
              - not_null

      - name: customer
        columns:
          - name: customerid # Utilizando o customerid no teste, pois cada Cliente deverá ter um id único.
            tests:
              - unique
              - not_null

      - name: store
        columns:
          - name: businessentityid # Utilizando o businessentityid no teste, pois cada Loja deverá ter um id único.
            tests:
              - unique
              - not_null

      - name: salesreason
        columns:
          - name: salesreasonid # Utilizando o salesreasonid no teste, pois cada Motivo de Venda deverá ter um id único.
            tests:
              - unique
              - not_null

      - name: stateprovince
        columns:
          - name: stateprovinceid # Utilizando o stateprovinceid no teste, pois cada Estado deverá ter um id único.
            tests:
              - unique
              - not_null

      - name: address
        columns:
          - name: addressid # Utilizando o addressid no teste, pois cada Estado deverá ter um id único.
            tests:
              - unique
              - not_null

      - name: countryregion
        columns:
          - name: countryregioncode # Utilizando o countryregioncode no teste, pois cada País deverá ter um id único.
            tests:
              - unique
              - not_null

      - name: product
        columns:
          - name: productid # Utilizando o productid no teste, pois cada Produto deverá ter um id único.
            tests:
              - unique
              - not_null

      - name: productsubcategory
        columns:
          - name: productsubcategoryid # Utilizando o productsubcategoryid no teste, pois cada Sub Categoria deverá ter um id único.
            tests:
              - unique
              - not_null

      - name: productcategory
        columns:
          - name: productcategoryid # Utilizando o productcategoryid no teste, pois cada Categoria deverá ter um id único.
            tests:
              - unique
              - not_null

      - name: salesorderheader
        description: Uma linha por pedido.
        columns:
          - name: salesorderid # Utilizando o salesorderid no teste, pois cada pedido deverá ter um id único.
            description: Chave primária da tabela de pedidos.
            tests:
              - unique
              - not_null

      - name: salesorderheadersalesreason
        description: Detalhe de motivo para cada pedido da tabela salesorderheader. 
        # Não será realizado teste por não haver uma chave única

      - name: salesorderdetail
        description: Uma linha por item de cada pedido.
        columns:
          - name: salesorderdetailid # Utilizando o salesorderdetailid no teste, pois cada salesorderdetailid deverá ter um id único.
            description: Chave de cada de item para cada pedido da tabela salesorderheader.
            tests:
              - unique
              - not_null

      - name: creditcard
        columns:
          - name: creditcardid # Utilizando o creditcardid no teste, pois cada Cartão deverá ter um id único.
            description: Chave primária da tabela de Cartão.
            tests:
              - unique
              - not_null