version: 2

sources:
  - name: erp
    schema: sap_adw
    description: Fonte de dados de vendas do SAP Adventure Works
    tables:
      - name: employee 
        columns:
          - name: businessentityid # Utilizando o businessentityid no teste, pois cada funcionário devera tem um id único.
            tests:
              - unique
              - not_null
      - name: person 
        columns:
          - name: businessentityid # Utilizando o businessentityid no teste, pois cada pessoa devera tem um id único.
            tests:
              - unique
              - not_null
      - name: salesperson
        columns:
          - name: rowguid # Utilizando o rowguid no teste, para previnir casos de um vendedor atuar em mais de um território o que geraria duas linhas nessa tabela com o mesmo businessentityid
            tests:
              - unique
              - not_null